second_shop/config/routes.rb
Rails.application.routes.draw do
  root :to => "backpacks#index"
  resources :laptops
   resources :backpacks
end

second_shop/app/models/backpack.rb
class Backpack < ActiveRecord::Base
end

second_shop/app/models/laptop.rb
class Laptop < ActiveRecord::Base
end

second_shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

second_shop/app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
	def destroy
		@backpack = Backpack.find(params[:id])
		@backpack.destroy

		redirect_to root_path
	end
	
	def index
		@backpacks = Backpack.all
	end

	def show 
		@backpack = Backpack.find(params[:id])
	end

	def new 
		@backpack = Backpack.new
	end

	def edit 
		@backpack = Backpack.find(params[:id])
	end

	def create 
		@backpack = Backpack.new(backpack_params)
		@backpack.save
		redirect_to backpack_path(@backpack)
	end

	def update 
		@backpack = Backpack.find(params[:id])
		@backpack.update(backpack_params)
		redirect_to backpack_path(@backpack)
	end

	private
	def backpack_params
		params.require(:backpack). permit(:color, :capacity, :pockets, :waterproof)
	end
end

second_shop/app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController

	def destroy
		@laptop = Laptop.find(params[:id])
		@laptop.destroy

		redirect_to root_path
	end
	
	def index
		@laptops = Laptop.all
	end

	def show 
		@laptop = Laptop.find(params[:id])
	end

	def new 
		@laptop = Laptop.new
	end

	def edit 
		@laptop = Laptop.find(params[:id])
	end

	def create 
		@laptop = Laptop.new(laptop_params)
		@laptop.save
		redirect_to laptop_path(@laptop)
	end

	def update 
		@laptop = Laptop.find(params[:id])
		@laptop.update(laptop_params)
		redirect_to laptop_path(@laptop)
	end

	private
	def laptop_params
		params.require(:laptop). permit(:brand, :model, :processorBrand, :ram, :price)
	end
end

second_shop/app/helpers/application_helper.rb
module ApplicationHelper
end

second_shop/app/helpers/backpacks_helper.rb
module BackpacksHelper
end

second_shop/app/helpers/laptops_helper.rb
module LaptopsHelper
end

second_shop/app/views/backpacks/edit.html.erb
<h1 align="center"><u>eCommerce Platform - Iteration 2</u></h1>

<%= form_for :backpack, url: backpack_path(@backpack), method: :patch do |f| %>

<p>
	<%= f.label :color %><br>
	<%= f.text_field :color %>
</p>

<p>
	<%= f.label :capacity %><br>
	<%= f.text_field :capacity %>
</p>

<p>
	<%= f.label :pockets %><br>
	<%= f.text_field :pockets %>
</p>

<p>
	<%= f.label :waterproof %><br>
	<%= f.text_field :waterproof %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

<p>
		<%= link_to 'Back', backpacks_path %>
	</p>

second_shop/app/views/backpacks/index.html.erb
<h1 align="center"><u>eCommerce Platform - Iteration 2</u></h1>

<% @backpacks.each do |backpack| %>
	<div>
		<%= backpack.color %>
		<%= backpack.capacity %>
		<%= backpack.pockets %>
		<%= backpack.waterproof %>
		<%= link_to 'Show', backpack_path(backpack) %>
		<%= link_to 'Edit', edit_backpack_path(backpack) %>
		<%= link_to 'Destroy', backpack_path(backpack), method: :delete, data: {confirm: 'Are you sure?'} %>
	</div>

<% end %>

	<p>
		<%= link_to 'New backpack', new_backpack_path %>
	</p>

second_shop/app/views/backpacks/new.html.erb
<h1 align="center"><u>eCommerce Platform - Iteration 2</u></h1>

<%= form_for @backpack do |f| %>

<p>
	<%= f.label :color %><br>
	<%= f.text_field :color %>
</p>

<p>
	<%= f.label :capacity %><br>
	<%= f.text_field :capacity %>
</p>

<p>
	<%= f.label :pockets %><br>
	<%= f.text_field :pockets %>
</p>

<p>
	<%= f.label :waterproof %><br>
	<%= f.text_field :waterproof %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

<p>
		<%= link_to 'Back', backpacks_path %>
	</p>

second_shop/app/views/backpacks/show.html.erb
<h1 align="center"><u>eCommerce Platform - Iteration 2</u></h1>

<h3>
	<strong>Mochila</strong>
	<%= @backpack.id %>
</h3>

<p>
	<strong>Color:</strong>
	<%= @backpack.color %>
</p>

<p>
	<strong>Capacity (in liters):</strong>
	<%= @backpack.capacity %>
</p>

<p>
	<strong>Number of Pockets:</strong>
	<%= @backpack.pockets %>
</p>

<p>
	<strong>If it is waterproof?:</strong>
	<%= @backpack.waterproof %>
</p>

<p>
	<%= link_to 'Edit', edit_backpack_path %>
	<%= link_to 'Back', backpacks_path %>
</p>

second_shop/app/views/laptops/edit.html.erb
<h1 align="center"><u>eCommerce Platform</u></h1>

<%= form_for :laptop, url: laptop_path(@laptop), method: :patch do |f| %>

<p>
	<%= f.label :brand %><br>
	<%= f.text_field :brand %>
</p>

<p>
	<%= f.label :model %><br>
	<%= f.text_field :model %>
</p>

<p>
	<%= f.label :processorBrand %><br>
	<%= f.text_field :processorBrand %>
</p>

<p>
	<%= f.label :ram %><br>
	<%= f.text_field :ram %>
</p>

<p>
	<%= f.label :price %><br>
	<%= f.text_field :price %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

<p>
		<%= link_to 'Back', laptops_path %>
	</p>

second_shop/app/views/laptops/index.html.erb
<h1 align="center"><u>eCommerce Platform</u></h1>

<% @laptops.each do |laptop| %>
	<div>
		<%= laptop.brand %>
		<%= laptop.model %>
		<%= laptop.processorBrand %>
		<%= laptop.ram %>
		<%= laptop.price %>
		<%= link_to 'Show', laptop_path(laptop) %>
		<%= link_to 'Edit', edit_laptop_path(laptop) %>
		<%= link_to 'Destroy', laptop_path(laptop), method: :delete, data: {confirm: 'Are you sure?'} %>
	</div>

<% end %>

	<p>
		<%= link_to 'New laptop', new_laptop_path %>
	</p>

	

second_shop/app/views/laptops/new.html.erb
<h1 align="center"><u>eCommerce Platform</u></h1>

<%= form_for @laptop do |f| %>

<p>
	<%= f.label :brand %><br>
	<%= f.text_field :brand %>
</p>

<p>
	<%= f.label :model %><br>
	<%= f.text_field :model %>
</p>

<p>
	<%= f.label :processorBrand %><br>
	<%= f.text_field :processorBrand %>
</p>

<p>
	<%= f.label :ram %><br>
	<%= f.text_field :ram %>
</p>

<p>
	<%= f.label :price %><br>
	<%= f.text_field :price %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

<p>
		<%= link_to 'Back', laptops_path %>
	</p>

second_shop/app/views/laptops/show.html.erb
<h1 align="center"><u>eCommerce Platform</u></h1>

<h3>
	<strong>Ordenador</strong>
	<%= @laptop.id %>
</h3>

<p>
	<strong>Brand:</strong>
	<%= @laptop.brand %>
</p>

<p>
	<strong>Model:</strong>
	<%= @laptop.model %>
</p>

<p>
	<strong>Processor Brand:</strong>
	<%= @laptop.processorBrand %>
</p>

<p>
	<strong>RAM:</strong>
	<%= @laptop.ram %>
</p>

<p>
	<strong>Price:</strong>
	<%= @laptop.price %>
</p>

<p>
	<%= link_to 'Edit', edit_laptop_path %>
	<%= link_to 'Back', laptops_path %>
</p>

second_shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>